name = "activelog-ai"
account_id = "049ff5e84ecf636b53b162cbb580aae6"
main = "src/worker.ts"
compatibility_date = "2024-12-01"

[[kv_namespaces]]
binding = "ACTIVELOG_KV"
id = "fd028413c2f049698518f32c63ec598e"
